In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('per.csv')

In [3]:
df.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [4]:
import hazm

In [5]:
df=df.drop(['NewsID','Date','Time'],axis=1)

In [6]:
df

Title  \
0      \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1      \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2      \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3      \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4      \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   
...                                                  ...   
10994              \n/گزارش/ «حقي» حق خود را با طلا گرفت   
10995  \nمدير تيم‌هاي ملي كشتي فرنگي: نفرات اول تا سو...   
10996  \nتساوي چلسي و ادامه صدرنشيني آرسنال تساوي اشت...   
10997  \nشكست ايران از پرتغال در آيينه‌ي خبرگزاري‌ها:...   
10998  \nهادي شكوري: صدر جدول را تصاحب كنيم ديگر آن ر...   

                                                    Body            Category  \
0      \nوزير علوم در جمع استادان نمونه كشور گفت: از ...           \nآموزشي-   
1      \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...           \nآموزشي-   
2      \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...           \nآموزشي-   
3                                                     \n  \nاجتماعي-خانواده-   
4      \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...           \nآموزشي-   
...                                                  ...                 ...   
10994  \nبه گزارش ايسنا، در كوران مسابقات دوچرخه سوار...   \nقهرماني-همگاني-   
10995  \nمحمد دليريان در گفت‌وگو با خبرنگار كشتي خبرگ...       \nورزشي-كشتي-   
10996  \nبه گزارش خبرگزاري دانشجويان ايران (ايسنا)، د...     \nورزشي-فوتبال-   
10997  \nبه گزارش خبرگزاري دانشجويان ايران (ايسنا)، ا...   \nجام جهاني 2010-   
10998  \nهادي شكوري در خصوص ديدار تيمش مقابل راه‌آهن ...     \nورزشي-فوتبال-   

       Category2  
0       \nآموزشي  
1       \nآموزشي  
2       \nآموزشي  
3      \nاجتماعي  
4       \nآموزشي  
...          ...  
10994    \nورزشي  
10995    \nورزشي  
10996    \nورزشي  
10997    \nورزشي  
10998    \nورزشي  

[10999 rows x 4 columns]

In [7]:
df['title_body'] = df['Title'] +' '+df['Body']


In [8]:
df=df.drop(['Title','Body'],axis=1)

In [9]:
df

Category  Category2  \
0               \nآموزشي-   \nآموزشي   
1               \nآموزشي-   \nآموزشي   
2               \nآموزشي-   \nآموزشي   
3      \nاجتماعي-خانواده-  \nاجتماعي   
4               \nآموزشي-   \nآموزشي   
...                   ...        ...   
10994   \nقهرماني-همگاني-    \nورزشي   
10995       \nورزشي-كشتي-    \nورزشي   
10996     \nورزشي-فوتبال-    \nورزشي   
10997   \nجام جهاني 2010-    \nورزشي   
10998     \nورزشي-فوتبال-    \nورزشي   

                                              title_body  
0      \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...  
1      \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...  
2      \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...  
3      \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...  
4      \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...  
...                                                  ...  
10994  \n/گزارش/ «حقي» حق خود را با طلا گرفت \nبه گزا...  
10995  \nمدير تيم‌هاي ملي كشتي فرنگي: نفرات اول تا سو...  
10996  \nتساوي چلسي و ادامه صدرنشيني آرسنال تساوي اشت...  
10997  \nشكست ايران از پرتغال در آيينه‌ي خبرگزاري‌ها:...  
10998  \nهادي شكوري: صدر جدول را تصاحب كنيم ديگر آن ر...  

[10999 rows x 3 columns]

In [10]:
df=df.drop('Category',axis=1)

In [11]:
df['Category2'] = df['Category2'].str.replace('\n', '')

In [12]:
df['title_body'] = df['title_body'].str.replace('\n', '')

In [13]:
df['title_body'] = df['title_body'].str.replace('/', '')

In [13]:
from hazm import word_tokenize

In [34]:
df['title_body_tokenized']=df['title_body'].apply(lambda x: word_tokenize(str(x)))

In [14]:
df

Category2                                         title_body
0        آموزشي  وزير علوم درجمع استادان نمونه: سن بازنشستگي اس...
1        آموزشي  گردهمايي دانش‌آموختگان موسسه آموزش عالي سوره ب...
2        آموزشي  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ا...
3       اجتماعي  همايش يكروزه آسيب شناسي مفهوم روابط عمومي در ب...
4        آموزشي  وضعيت اقتصادي و ميزان تحصيلات والدين از مهمتري...
...         ...                                                ...
10994     ورزشي  گزارش «حقي» حق خود را با طلا گرفت به گزارش ايس...
10995     ورزشي  مدير تيم‌هاي ملي كشتي فرنگي: نفرات اول تا سوم ...
10996     ورزشي  تساوي چلسي و ادامه صدرنشيني آرسنال تساوي اشتوت...
10997     ورزشي  شكست ايران از پرتغال در آيينه‌ي خبرگزاري‌ها: د...
10998     ورزشي  هادي شكوري: صدر جدول را تصاحب كنيم ديگر آن را ...

[10999 rows x 2 columns]

In [15]:
import nltk 
from nltk.corpus import stopwords
from string import punctuation

In [16]:
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Kalimist\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
with open('stopwords.txt', 'r', encoding='utf-8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسیب پذیرند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن گاه',
 'آنان',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'اتفاقا',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احیاناً',
 'اخیر',
 'اخیراً',
 'اری',
 'از',
 'از آن پس',
 'از جمله',
 'ازاین رو',
 'ازجمله',
 'ازش',
 'اساسا',
 'اساساً',
 'است',
 'استفاد',
 'استفاده',
 'اسلامی اند',
 'اش',
 'اشتباها',
 'اشکارا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اعلام',
 'اغلب',
 'افزود',
 'افسوس',
 'اقل',
 'اقلیت',
 'الا',
 'الان',
 'البته',
 'البتّه',
 'الهی',
 'الی',
 '

In [19]:
df['title_body'] = df['title_body'].replace('\u200c', '')

In [20]:
df

Category2                                         title_body
0        آموزشي  وزير علوم درجمع استادان نمونه: سن بازنشستگي اس...
1        آموزشي  گردهمايي دانش‌آموختگان موسسه آموزش عالي سوره ب...
2        آموزشي  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ا...
3       اجتماعي  همايش يكروزه آسيب شناسي مفهوم روابط عمومي در ب...
4        آموزشي  وضعيت اقتصادي و ميزان تحصيلات والدين از مهمتري...
...         ...                                                ...
10994     ورزشي  گزارش «حقي» حق خود را با طلا گرفت به گزارش ايس...
10995     ورزشي  مدير تيم‌هاي ملي كشتي فرنگي: نفرات اول تا سوم ...
10996     ورزشي  تساوي چلسي و ادامه صدرنشيني آرسنال تساوي اشتوت...
10997     ورزشي  شكست ايران از پرتغال در آيينه‌ي خبرگزاري‌ها: د...
10998     ورزشي  هادي شكوري: صدر جدول را تصاحب كنيم ديگر آن را ...

[10999 rows x 2 columns]

In [47]:
len(stopwords)

1316

In [21]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

1495

In [27]:
from hazm import word_tokenize
from hazm import Stemmer
st=Stemmer()

In [28]:
corpus=[]
for w in range(len(df['title_body'])) :
    msg=df['title_body'][w]
    msg=word_tokenize(msg)
    msg=[st.stem(word) for word in msg if not word in stopwords]
    msg=" ".join(msg)
    corpus.append(msg)

In [30]:
corpus

['وزير علو درجمع استاد نمونه سن بازنشستگي استاد نمونه 70 سال افزاي مي\u200cيابد دانشگاه بايد مهد چالشهاي گفتماني خط دهنده برنامه\u200cريز جري سياسي وزير علو جمع استاد نمونه كشور استاد نمونه كشور انتظار مي\u200cرود كه رويكرد دانايي محوري گف علمي يك بحث فرهنگي دانشگاه توسعه رونق بخشند گزار سرويس صنفي آموزشي خبرگزاري دانشجوي اير ايسنا دك محمد مهدي زاهدي اولين مجمع عمومي استاد نمونه دانشگاه\u200cهاي كشور كه دانشگاه تهر برگزار توصيه تلا براي دانايي محوري توسعه گف علمي معني تمايل مباحث سياسي نيس بلكه برعكس دانشگاه بايد مهد چالشهاي گفتماني ولي اين امر معني نيس كه دانشگاه ابزار دس سياسيون قرار بگيرد وي تأكيد كرد دانشگاه نبايد تأثير القائ سياسي قرار بگيرد بلكه بايد خط دهنده برنامه\u200cريز جري سياسي مهمترين عنصر پياده اين آر دانشجوي اعضاي هي علمي دانشگاه رأس استاد نمونه وزير علو ذكر اين نكته كه جامعه اطلاعاتي نمي\u200cتو هيچ تفكري تهديد ارعاب حاك كرد دانشگاه بايد پرچمدار كرسيهاي آزاد انديشي حاكمي دانايي محوري بايد توجه داشته_باشند كه ناخودآگاه تأثير جوسازي القائ رسانه قرار نگيرند دك زاهدي اقدا 

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tf=TfidfVectorizer()
X=tf.fit_transform(corpus).toarray()

In [38]:
X.shape

(10999, 61621)

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(df['Category2'])

In [41]:
len(y)

10999

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [43]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,y_train)

SVC()

In [44]:
from sklearn.metrics import classification_report ,confusion_matrix
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.86       235
           1       0.64      0.65      0.64       250
           2       0.79      0.79      0.79       253
           3       0.85      0.92      0.89       263
           4       0.92      0.89      0.90       263
           5       0.81      0.73      0.76       245
           6       0.81      0.76      0.78       249
           7       0.84      0.86      0.85       238
           8       0.86      0.89      0.88       255
           9       0.95      0.93      0.94       252
          10       0.96      0.96      0.96       247

    accuracy                           0.84      2750
   macro avg       0.84      0.84      0.84      2750
weighted avg       0.84      0.84      0.84      2750

[[213   4   1   4   0   2   8   3   0   0   0]
 [ 17 162  16   9   5   5   9  12  12   2   1]
 [  0  26 199   5   0   4   7   7   3   1   1]
 [  0   8   3 243   0   0   7   1   0   0   1]